### PR TITLE
Patch to latest v4-dev

### LINKED ISSUE #8: OverlayScrollbars now fixed, plz rebuild demo
@danny007in approved my PR, so if you merge and build, the demo should work again.

Currently, none of the submenus work because of it.

image

### PR DESCRIPTION
**Pull request by MGatner**
Fixes #8.

### CODE REVIEW

**Comment by MGatner** [comment]
@tacman Please review.

**Comment by tacman** [comment]
No, the JS isn't loading, so the submenus don't work.

image

**Comment by MGatner** [comment]
This will need to be fixed upstream, as this is the very latest build from the `v4-dev` branch. I will leave this open until then.

**Comment by MGatner** [comment]
@tacman Are you sure you are using this branch to test? Your image shows the camelcase folder name `overlayScrollbars` but the HTML file definitely has the correct lowercase:
```html
<!-- overlayScrollbars -->
<link rel="stylesheet" href="./vendor/overlayscrollbars/css/OverlayScrollbars.min.css">
```
**index2.html:33**

**Comment by MGatner** [comment]
The second error in your image is a problem with AdminLTE - there is no root **js/** folder, it should be **assets/js/**:
```html
<!-- AdminLTE App -->
<script src="./js/adminlte.js"></script>
```
**index2.html:1246**

**Comment by tacman** [comment]
I'm using your demo link:  https://adminlte4.gatner.be/

**Comment by MGatner** [comment]
Your page must be cached then because the demo is using this branch and the folder name is definitely update. Try force reloading or opening a different browser.

**Comment by tacman** [comment]
Hmm, I've done both those things, still not seeing anything.

```
 curl https://adminlte4.gatner.be/ | grep adminlte.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33278  100 33278    0     0  79233      0 --:--:-- --:--:-- --:--:-- 79233
<script src="./js/adminlte.js"></script>


tac@pop-os:~/survos/projects/news$ curl https://adminlte4.gatner.be/js/adminlte.js
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.46 (Ubuntu) Server at adminlte4.gatner.be Port 443</address>
</body></html>
```

**Comment by MGatner** [comment]
@tacman That is expected. You've reported two issues here:
* 1) File not found: **vendor/overlayScrollbars/css/OverlayScrollbars.min.css**
* 2) File not found: **js/adminlte.js**

The first should not be an issue with this branch (this is what you fixed in the parent project); the second is still an issue in the parent project, though I have submitted a PR to fix it (scroll up in this PR to see the reference).

**Comment by themikem** [comment]
Note that I'm getting a 404 for https://adminlte4.gatner.be/assets/js/adminlte.js if I try to get the file directly as well...

So maybe both the URL is wrong and the adminlte.js file is also missing...?

**Comment by MGatner** [comment]
You're right! It isn't there either. We will need the maintainers to figure this one out - no activity on my PR yet but hopefully when they see that they can say more. I'm not familiar with how the build process is supposed to generate these files.

**Comment by tacman** [comment]
I have a version of their package that includes those files:

https://yarnpkg.com/package/adminlte4-bs5

It's been what I've been using for my projects, it's identical to
ColorLib's, but has the scrollbar fix and a dist directory (created by gulp
build).  Then I add it to my projects with yarn add adminlte4-bs5.

It's functional for me, but I don't really know what I'm doing.  I've
merged in the latest changes locally, but for some reason I can no longer
publish the package (even switching node versions, etc.)

error Couldn't publish package: "https://registry.yarnpkg.com/adminlte4-bs5:
ESOCKETTIMEDOUT"
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about
this command.

I think there's a fundamental problem, though, which is that I want to use
it as a simple package and extend from it, whereas their philosophy is
something like using it as a base to build your own package.  For example,
I've put the javascript in another repository and include it separately,
largely because I can't figure out how to incorporate the typescript
build.

Tac

**Comment by tacman** [comment]
This is what I use now, it's just the ts=>js in a separate file.  I know
that it's not very elegant, but it does get the menus and other things
working.

https://github.com/survos/BaseBundle/blob/master/src/Resources/assets/js/adminlte.js

**Comment by MGatner** [comment]
Glad you've got something working! I'm really not trying to complicate this workflow though: I just take what they have on `v4-dev`, compile it, and publish it. If there are broken pieces then it should be an impetus to make fixes upstream. Honestly I'm a bit sad BootStrap 5 has been out this long and my admin-dashboard-of-choice still does not have a compatible release.

**Comment by tacman** [comment]
Ditto.  But it took years for colorlib to have a release version that
supported version 4.

Obviously, it's a lot of work, and I am super-appreciative of what they've
done, but I agree with you about being disappointed/sad.

@kevinpapst had a terrific bundle for AdminLTE and Symfony 4.  Since I'm
using Symfony 5, I tweaked his bundle, but it became a mess because the
site was using different versions of bootstrap.  I eventually got it
working, but really wanted to use bootstrap 5, even if just for the basic
layout and menus.

I've tried most of the other bs5 themes, even paid for some of them, but
frequently their free versions lack some critical features that my open
source projects need, and it was too difficult to keep track of everything.

**Comment by MGatner** [comment]
You and I are in the same boat! I'm a backend PHP developer who ends up doing most of my own frontend reluctantly. BootStrap is a lifesaver. This past summer I went on a foray to find an alternative admin dashboard that would support BS5 but ultimately was disappointed with the ones I found on one front or another.

If I had more skills/time I would try to move the ball forward on AdminLTE, but throwing up this repo was the extent of what I could handle. Here's hoping!

**Comment by kevinpapst** [comment]
Why not jump in and lets work together on: https://github.com/kevinpapst/AdminLTEBundle ?

**Comment by themikem** [comment]
If someone can give me a few more sentences on what the “js config” piece that is missing actually is, I’ll be happy to assign some dev resources to it if it will help. I have adopted AdminLTE as a key library, so right there with you with things being broken. 

Already took a look at the issues here and at the main repo, and in discord, but still not clear on scope of the “js config” task. But if someone can explain it, happy to help out and take a run at fixing it if it unblocks the build and/or release process while others are tackling the v3 release

**Comment by tacman** [comment]
As you know, I had a fork for your awesome bundle for quite a while, to support Symfony 5, but I really, really wanted to use Bootstrap 5, and it was nearly impossible to support different versions of Bootstrap and different versions of Symfony.  

FOSUserBundle FINALLY supports Symfony 5, until recently it had not, which was a dealbreaker for me (thus the fork).  But FOSUserBundle is no longer recommended, in fact, Symfony has a "new" security system which is the best practice for new projects.  I'm still integrating it with my projects.

With Symfony 6 less than 7 weeks away, I'd much prefer to work on an admin bundle that prioritized that, even requiring PHP 8, and using stimulus for the javascript (a game-changer for me!  No more jQuery for simple interactions!).
The bundle I use for my projects is SurvosBaseBundle, which is not clean enough for anyone else to use but all my projects are based on it.  Over the years, it has had dependencies on most Open Source admin bundles, but eventually I moved almost everything I needed into it, for consistency with Symfony 5 and Bootstrap 5. 

But yes, AdminLTEBundle is great, and I agree it'd be better to work on it.  We can move this to a thread in that bundle.
In this thread, https://github.com/kevinpapst/AdminLTEBundle/issues/161, you said 

    Using AdminLTE v2, it works perfectly fine and is stable.   
    There is no need to upgrade to the latest lib versions only for sake of upgrading.

Alas, that's exactly what I want to do -- update to the latest libraries.  Especially Symfony and Boostrap, the cornerstones of my development.

**Comment by tacman** [comment]
I've started a thread in AdminLTEBundle to brainstorm: https://github.com/kevinpapst/AdminLTEBundle/issues/170

**Comment by tacman** [comment]
> If someone can give me a few more sentences on what the “js config” piece that is missing actually is, I’ll be happy to assign some dev resources to it if it will help. 

In the latest version from colorlib, the libraries changes to typescript.  So somewhere along the line the typescript files need to be compiled in JS.  My hack was to create a v4-dist branch, run gulp build, and check in the compiled JS.  I _think_ the correct solution is to compile those field during "yarn install", but I don't know how.

**Comment by MGatner** [comment]
Danny fixed this! https://github.com/ColorlibHQ/AdminLTE/commit/a83b521bdabe73bc2ca8486378a2be2ee7cfce47

Looking at the changes it appears that the JS distribution folder was left off the gulp index. I will rebuild and update this PR later on desktop.

**Comment by MGatner** [comment]
Latest version rebuilt and published - all looks good! https://adminlte4.gatner.be

**Review by sins921 — APPROVED** [review]

**Pull request merged**
